### ISSUE TITLE
Go Module on Vercel for theme

### ISSUE THREAD

**Issue by enguerran** [forestryio/hugo-ananke-forestry#2]
I tried to deploy this Hugo site on Vercel, but the [Go runtime is only available for the Serverless Functions](https://vercel.com/docs/runtimes#official-runtimes/go). So the configuration of the theme with the Go module, [recommended by Hugo](https://gohugo.io/hugo-modules/use-modules/#use-a-module-for-a-theme), doesn't work when you need to deploy it on Vercel.
I updated my website to [use the git sub-module, the old fashioned way](https://gohugo.io/getting-started/quick-start/#step-3-add-a-theme). I'd like to spread the word in this project for the next user.

**Comment by DirtyF** [comment]
Right, you need to install Go, Vercel has plans to support Go for builds according to https://github.com/vercel/vercel/discussions/5049

Here's an example or how to install Go on Vercel (thanks to @Narno for the script)

- https://github.com/jamstatic/jamstatic-fr/blob/master/now.json
- https://github.com/jamstatic/jamstatic-fr/blob/master/now-build.sh

**Comment by DirtyF** [comment]
I've removed the mention of the Vercel deployment for now, too much overhead for a majority of users looking to deploy a site in 5 minutes or less. I'll add it back when they had proper support. Thanks for the notice.
